apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: hellogo
    version: v3
  name: hellogo-v3
  namespace: demo
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: hellogo:v3
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/AlexonOliveiraRH/hellogo.git
    contextDir: hellogo-v3
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: golang:latest
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
