apiVersion: apps/v3
kind: Deployment
metadata:
  annotations:
  labels:
    app: hellogo
    version: v3
  name: hellogo-v3
  namespace: demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: hellogo-v3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: hellogo
        deployment: hellogo-v3
        version: v3
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/cicd/hellogo:latest
        imagePullPolicy: IfNotPresent
        name: hellogo-v3
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
