apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: hellogo
    version: v1
  name: hellogo-v1
  namespace: demo
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: hellogo:v1
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/AlexonOliveiraRH/hellogo.git
    contextDir: hellogo-v1
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: golang:1.18-ubi8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
